routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', 'FrontEndPagesController@index');
Route::get('/constitution', 'FrontEndPagesController@constitution');
Route::get('/locations', 'FrontEndPagesController@locations');
Route::get('/contact-us', 'FrontEndPagesController@contactus');*/

// Frontend routes

/*
|--------------------------------------------------------------------------
| Web Routes Social Media and front-end
|--------------------------------------------------------------------------
|
| CMS Routes
|
|
|
*/
Route::get('/',[
    'uses' => 'CMSController@index',
    'as' => 'frontend-home',
]);

Route::get('/page/{pageSlug}',[
    'uses' => 'CMSController@cms',
]);

Route::get('/constitution', 'FrontEndPagesController@constitution');
Route::get('/locations', 'FrontEndPagesController@locations');
Route::get('/contact-us', 'FrontEndPagesController@contactus');
Route::get('/gallery', 'FrontEndPagesController@gallery');
Route::get('/meeting', 'FrontEndPagesController@meeting');

//Search
Route::get('/search', 'SearchController@search');

Route::post('/save-contact-message',[
    'uses' => 'ContactController@store',
    'as' => 'post.contact-message',
]);


/******************************************************
 *     Auth Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['middleware' => ['web']], function() {


// Login Routes...
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);



// Registration Routes...
    //Route::get('register', ['as' => 'show.register', 'uses' => 'Auth\RegisterController@showRegisterationForm']);
    //Route::post('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@register']);


    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

    //Email verification route
    $this->get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
    $this->get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
    $this->get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');


});


/******************************************************
 *     Member Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['prefix' => 'member','as' => 'member.'],function () {


    Route::get('',[
        'uses'=>'Member\DashboardController@index',
        'as'=>'show.index',
    ]);


    ////////// Manage Meetings //////////
    Route::get('/meetings',[
        'uses'=>'Member\MeetingController@index',
        'as'=>'meetings.index',
    ]);


    Route::get('/meetings/{id}',[
        'uses'=>'Member\MeetingController@show',
        'as'=>'meetings.show',
    ]);

    ////////// Manage Matrices //////////
    Route::get('/matrices',[
        'uses'=>'Member\MatrixController@index',
        'as'=>'matrices.index',
    ]);
    Route::get('/matrices/{id}',[
        'uses'=>'Member\MatrixController@show',
        'as'=>'matrices.show',
    ]);

    ////////// Manage Matrix tables //////////
    Route::get('/matrix/table',[
        'uses'=>'Member\MatrixTableController@index',
        'as'=>'matrix.tables.index',
    ]);



    ////////// Manage Competency Areas //////////
    Route::get('/competency-areas/{id}',[
        'uses'=>'Member\CompetencyAreaController@show',
        'as'=>'competency-areas.show',
    ]);

    ////////// Manage Test //////////
    /// Route::get('/matrices',[
    Route::get('/tests',[
        'uses'=>'Member\TestController@index',
        'as'=>'tests.index',
    ]);

    Route::get('/tests/{id}',[
        'uses'=>'Member\TestController@show',
        'as'=>'tests.show',
    ]);

    Route::post('/tests',[
        'uses'=>'Member\TestController@store',
        'as'=>'tests.store',
    ]);

    Route::put('/tests/{id}',[
        'uses'=>'Member\TestController@update',
        'as'=>'tests.update',
    ]);
    Route::delete('/tests/{id}',[
        'uses'=>'Member\TestController@destroy',
        'as'=>'tests.destroy',
    ]);


    ////////// Manage Meetings //////////

    Route::get('/test/publications',[
        'uses'=>'Member\TestPublicationController@index',
        'as'=>'test.publications.index',
    ]);

    Route::post('/test/publications',[
        'uses'=>'Member\TestPublicationController@store',
        'as'=>'test.publications.store',
    ]);

    Route::delete('/test/publications/{id}',[
        'uses'=>'Member\TestPublicationController@destroy',
        'as'=>'test.publications.destroy',
    ]);

});


/******************************************************
 *     Admin Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['prefix' => 'admin','as' => 'admin.'],function () {

    Route::get('',[
        'uses'=>'Backend\DashboardController@index',
        'as'=>'show.index',
    ]);

    Route::get('login',[
        'uses'=>'Auth\Admin\LoginController@showLogin',
        'as'=>'show.login',
        //'middleware'=>'auth:admin',
    ]);

    Route::post('login',[
        'uses'=>'Auth\Admin\LoginController@login',
        'as'=>'login',
    ]);

    Route::get('logout',[
        'uses'=>'Auth\Admin\LoginController@logout',
        'as'=>'logout',
        //'middleware'=>'auth:admin',
    ]);

        /*
    | Web Routes Admin backend
    |--------------------------------------------------------------------------
    | CMS level routes
    */
    //
    Route::get('manage-cms',array(
        'uses'=>'Backend\CMSController@showManageCMS',
        'as'=>'show.manage-cms',
        'middleware' => 'auth:admin',
    ));

    //Page Preview
    Route::get('page-preview/{pageSlug}',[
        'uses' => 'Backend\CMSController@cms',
        'as'=>'show.page-preview',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/page-preview/',[
        'uses' => 'Backend\CMSController@index',
        'as'=>'show.page-preview-home',
        'middleware' => 'auth:admin',
    ]);


    //publishContent
    Route::post('publish_content/{id}',array(
        'uses'=>'Backend\CMSController@publishContent',
        'as'=>'publish_content',
        'middleware' => 'auth:admin',
    ));



    //nEW ROUTE FOR MENUS

    Route::prefix('ajax/page')->group(function () {
        Route::post('all',array(
            'uses'=>'Backend\CMSController@getMenus',
            'as'=>'ajax.get.pages',
            'middleware' => 'auth:admin',
        ));
        Route::post('create',array(
            'uses'=>'Backend\CMSController@createMenu',
            'as'=>'ajax.create.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('update',array(
            'uses'=>'Backend\CMSController@updateMenu',
            'as'=>'ajax.update.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('delete',array(
            'uses'=>'Backend\CMSController@deleteMenu',
            'as'=>'ajax.delete.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('dnd',array(
            'uses'=>'Backend\CMSController@dragAndDropMenu',
            'as'=>'ajax.dnd.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('detail',array(
            'uses'=>'Backend\CMSController@getPageDetail',
            'as'=>'ajax.get.page-detail',
            'middleware' => 'auth:admin',
        ));
        Route::post('update-page-detail',array(
            'uses'=>'Backend\CMSController@updatePage',
            'as'=>'ajax.update.page-detail',
            'middleware' => 'auth:admin',
        ));

        //footer menu
        Route::post('footer/all',array(
            'uses'=>'Backend\CMSController@getFooterMenus',
            'as'=>'ajax.get.footer-menus',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/create',array(
            'uses'=>'Backend\CMSController@createFooterMenu',
            'as'=>'ajax.create.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/update',array(
            'uses'=>'Backend\CMSController@updateFooterMenu',
            'as'=>'ajax.update.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/delete',array(
            'uses'=>'Backend\CMSController@deleteFooterMenu',
            'as'=>'ajax.delete.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/dnd',array(
            'uses'=>'Backend\CMSController@dragAndDropFooterMenu',
            'as'=>'ajax.dnd.footer-menu',
            'middleware' => 'auth:admin',
        ));
        //publishContent
        Route::post('publish',array(
            'uses'=>'Backend\CMSController@publishContent',
            'as'=>'ajax.publish.page',
            'middleware' => 'auth:admin',

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Admin;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class AdminController extends Controller
{
    public function index()
    {
        $admins = Admin::all();
        return view('backend.admin.index',compact('admins'));
    }

    public function create()
    {
        $roles = Role::all();
        return view('backend.admin.create',compact('roles'));

    }

    public function edit($id)
    {
        //Edit Admin
        $admin =  Admin::findOrFail($id);
        $roles = Role::all();
        return view('backend.admin.edit',compact('admin','roles'));

    }

    public function store(Request $request)
    {


        $admin =  new Admin();
        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'email|max:255|unique:admins',

            'password' => 'required|string|min:6',

        ]);

        $admin->name =  $request->input('name');
        $admin->email = $request->input('email');
        $admin->role_id = $request->input('role_id');


        $admin->password = bcrypt($request->input('password'));

        $admin->save();


        $data = array('name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => $request->input('password')
        );

        Mail::send('emails.admin_details', $data, function ($message) {
            $message->to(Input::get('email'), 'HVSIA')
                ->subject('Administrator Details');
            $message->from(env('MAIL_FROM_ADDRESS', 'admin@hvsia.com'), 'HVSIA');
        });


        Session::flash('message', 'Administrator successfully Created!');
        return redirect()->route('admin.admins.index');

    }

    public function destroy(Request $request){
        $admin = Admin::findOrFail($request->id);
        if($admin->delete()){
            Session::flash('message','Admin Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        Admin::where('id',$id)->update($data);

        return redirect()->back()->with('message','Admin successfully Updated!');

    }
}

app/Http/Controllers/Backend/CompetencyAreaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\CompetencyArea;
use App\Role;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use App\FocusArea;

class CompetencyAreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $competency_areas = CompetencyArea::all();
        return view('backend.competency-area.index',compact('competency_areas'));
    }

    public function create()
    {
        return view('backend.competency-area.create');

    }

    public function edit($id)
    {
        //Edit CompetencyArea
        $competency_area =  CompetencyArea::findOrFail($id);
        return view('backend.competency-area.edit',compact('competency_area'));

    }

    public function store(Request $request)
    {

        $competency_area =  new CompetencyArea();
        $this->validate($request, [
            'name' => 'required|max:255',
        ]);

        $competency_area->name =  $request->input('name');

        $competency_area->save();


        return redirect()->route('admin.competency-areas.index');

    }

    public function show(Request $request,$id)
    {
        $competency_area = CompetencyArea::findOrFail($id);
        $focus_area = FocusArea::findOrFail($request->focus_area_id);
        return view('backend.competency-area.show',compact('competency_area','focus_area'));
    }

    public function destroy($id){
        $competency_area = CompetencyArea::findOrFail($id);
        if($competency_area->delete()){
            Session::flash('message','CompetencyArea Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        CompetencyArea::where('id',$id)->update($data);

        return redirect()->route('admin.competency-areas.index')->with('message','CompetencyArea successfully Updated!');

    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct() {
        $this->middleware('auth:admin');
    }

    public function  index(){
        
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/FocusAreaImageUploadController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FocusArea;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class FocusAreaImageUploadController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function update(Request $request,$id){

        $focus_area = FocusArea::findOrFail($id);
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileName = $focus_area->generateRandomName($focus_area->name, $file);
            Storage::disk('public')->put(config('filesystems.storage.focus_area_image_path') . $fileName, file_get_contents($file));

            $focus_area->image = $fileName;
            $focus_area->save();

        }

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/LocationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Location;
use App\Role;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class LocationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function index()
    {
        $locations = Location::all();
        return view('backend.location.index',compact('locations'));
    }

    public function create()
    {
        return view('backend.location.create');

    }

    public function edit($id)
    {
        //Edit Location
        $location =  Location::findOrFail($id);
        return view('backend.location.edit',compact('location'));

    }

    public function store(Request $request)
    {

        $location =  new Location();
        $this->validate($request, [
            'country' => 'required|max:255',
            'organization' => 'required|max:255',
        ]);

        $location->country =  $request->input('country');
        $location->organization =  $request->input('organization');


        $location->save();


        return redirect()->route('admin.locations.index');

    }

    public function destroy($id){
        $location = Location::findOrFail($id);
        if($location->delete()){
            Session::flash('message','Location Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        Location::where('id',$id)->update($data);

        return redirect()->route('admin.locations.index')->with('message','Location successfully Updated!');

    }
}

resources/views/backend/meeting/index.blade.php
@extends('layouts.backend.main')

@section('css')
    {{-- @include('layouts.admin_css.faq_css')--}}

    <link href="{{asset('Back-Assets/assets/plugins/gritter/css/jquery.gritter.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="{{asset('Back-Assets/css/custom.css')}}" type="text/css" media="screen">

@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Manage Meetings</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Meetings</a></li>
                <li class="breadcrumb-item active">Manage</li>
            </ol>
        </div>

    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
    @include('layouts.frontend.inc.response')
        <!-- begin row -->
        <div class="row">
            <!-- begin col-12 -->
            <div class="col-md-6" >
                <!-- begin panel -->
                <div class="card" data-sortable-id="tree-view-4">
                    <div class="card-body" style="padding: 0px!important;">
                        <ul class="nav nav-tabs customtab" role="tablist">
                            <li class="nav-item"> <a class="nav-link active show" data-toggle="tab" href="#home2" role="tab" aria-selected="true"><span class="hidden-sm-up"><i class="ti-home"></i></span> <span class="hidden-xs-down">Upcoming Meetings</span></a> </li>
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane active show" id="home2" role="tabpanel">
                                <div class="p-20" style="margin-top: 5%">
                                    <div class="table-responsive">
                                        <table  class="table table-striped">
                                            <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Date</th>
                                                <th>Time</th>
                                                <th class="text-nowrap">Action</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($upcoming_meetings as $row)
                                                <tr>
                                                    <td>{{str_limit($row->title,10)}}</td>
                                                    <td>{{$row->date}}</td>
                                                    <td>{{$row->time_start}}</td>
                                                    <td class="text-nowrap">
                                                        <a href="{{route('admin.meetings.edit',['id' => $row->id])}}" data-toggle="tooltip" data-original-title="Edit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                                        <a href="#modal-dialog"  data-id = "{{$row->id}}"  data-toggle="modal" style="width:100%" title="Delete"  id="delete-admin" class="trigger-modal"> <i class="fa fa-close text-danger"></i> </a>
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>



                </div>
                <!-- end panel -->
            </div >
            <div class="col-md-6">
                <!-- begin panel -->
                <div class="card" data-sortable-id="tree-view-4">
                    <div class="card-body"  style="padding: 0px!important">
                        <ul class="nav nav-tabs customtab" role="tablist">
                            <li class="nav-item"> <a class="nav-link active show" data-toggle="tab" href="#home4" role="tab" aria-selected="true"><span class="hidden-sm-up"><i class="ti-home"></i></span> <span class="hidden-xs-down">Concluded Meetings</span></a> </li>
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane active show" id="home4" role="tabpanel">
                                <div class="p-20" style="margin-top: 5%" >
                                    <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Concluded Date</th>

                                            <th width="6%"></th>

                                        </tr>
                                        </thead>
                                        <tbody>

                                            @foreach($past_meetings as $row)
                                                <tr>
                                                    <td>{{str_limit($row->title,10)}}</td>
                                                    <td>{{$row->date}}</td>

                                                    <td>
                                                        <div class="btn-group" role="group" aria-label="Basic example">
                                                            <a href="{{route('admin.meetings.show',['id' => $row->id])}}" type="button" class="btn btn-secondary">View</a>
                                                            <a href="{{route('admin.meetings.edit',['id' => $row->id])}}" data-toggle="tooltip" data-original-title="Edit" class="btn btn-outline-success"><i class="fa fa-pencil text-inverse"></i> </a>
                                                            <a href="#modal-dialog"  data-id = "{{$row->id}}"  data-toggle="modal"  data-original-title="Delete" style="width:100%" title="Delete"  id="delete-admin" class="trigger-modal btn btn-outline-danger"> <i class="fa fa-close text-danger"></i> </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>



                </div>
                <!-- end panel -->
            </div>
            <!-- end col-6 -->
        </div>
        <!-- end row -->
    </div>

    <!--====================================== #modal-dialog ========================================-->
    <div class="modal fade" id="modal-dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Meeting</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <p>
                        Are you sure you want to delete this Meeting
                    </p>
                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-white"  data-dismiss="modal">Close</a>
                    <form action="{{route('admin.meetings.destroy')}}" method="post">
                        {{csrf_field()}}
                        @method('DELETE')
                        <input type="hidden"  name="id" id="admin-id" value="1">
                        <input type="submit" class="btn btn-danger" id="delete" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- #modal-without-animation -->

@endsection

@section('script')
    {{--@include('layouts.admin_script.faq_script')--}}

    <script src="{{asset('Back-Assets/assets/plugins/jquerytree/jquery.tree.min.js')}}"></script>
    <script src="{{asset('Back-Assets/js/custom.min.js')}}"></script>
    <script src="{{asset('Back-Assets/js/jasny-bootstrap.js')}}"></script>

    <script src="{{asset('Back-Assets/assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function(settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function(group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function() {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
        $('#example233').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });

        $('.trigger-modal').on('click', function () {
            var id = $(this).attr('data-id');
            $('#admin-id').val(id);
            $('#modal-dialog').modal('show');

        });
    </script>
@endsection