routes/web.php
    'uses' => 'CMSController@index',
    'as' => 'frontend-home',
]);

Route::get('/page/{pageSlug}',[
    'uses' => 'CMSController@cms',
]);

Route::get('/constitution', 'FrontEndPagesController@constitution');
Route::get('/locations', 'FrontEndPagesController@locations');
Route::get('/contact-us', 'FrontEndPagesController@contactus');
Route::get('/gallery', 'FrontEndPagesController@gallery');
Route::get('/meeting', 'FrontEndPagesController@meeting');

//Search
Route::get('/search', 'SearchController@search');

Route::post('/save-contact-message',[
    'uses' => 'ContactController@store',
    'as' => 'post.contact-message',
]);


/******************************************************
 *     Auth Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['middleware' => ['web']], function() {


// Login Routes...
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);



// Registration Routes...
    //Route::get('register', ['as' => 'show.register', 'uses' => 'Auth\RegisterController@showRegisterationForm']);
    //Route::post('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@register']);


    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

    //Email verification route
    $this->get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
    $this->get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
    $this->get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');


});


/******************************************************
 *     Member Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['prefix' => 'member','as' => 'member.'],function () {


    Route::get('',[
        'uses'=>'Member\DashboardController@index',
        'as'=>'show.index',
    ]);


    ////////// Manage Meetings //////////
    Route::get('/meetings',[
        'uses'=>'Member\MeetingController@index',
        'as'=>'meetings.index',
    ]);


    Route::get('/meetings/{id}',[
        'uses'=>'Member\MeetingController@show',
        'as'=>'meetings.show',
    ]);

    ////////// Manage Matrices //////////
    Route::get('/matrices',[
        'uses'=>'Member\MatrixController@index',
        'as'=>'matrices.index',
    ]);
    Route::get('/matrices/{id}',[
        'uses'=>'Member\MatrixController@show',
        'as'=>'matrices.show',
    ]);

    ////////// Manage Matrix tables //////////
    Route::get('/matrix/table',[
        'uses'=>'Member\MatrixTableController@index',
        'as'=>'matrix.tables.index',
    ]);



    ////////// Manage Competency Areas //////////
    Route::get('/competency-areas/{id}',[
        'uses'=>'Member\CompetencyAreaController@show',
        'as'=>'competency-areas.show',
    ]);

    ////////// Manage Test //////////
    /// Route::get('/matrices',[
    Route::get('/tests',[
        'uses'=>'Member\TestController@index',
        'as'=>'tests.index',
    ]);

    Route::get('/tests/{id}',[
        'uses'=>'Member\TestController@show',
        'as'=>'tests.show',
    ]);

    Route::post('/tests',[
        'uses'=>'Member\TestController@store',
        'as'=>'tests.store',
    ]);

    Route::put('/tests/{id}',[
        'uses'=>'Member\TestController@update',
        'as'=>'tests.update',
    ]);
    Route::delete('/tests/{id}',[
        'uses'=>'Member\TestController@destroy',
        'as'=>'tests.destroy',
    ]);


    ////////// Manage Meetings //////////

    Route::get('/test/publications',[
        'uses'=>'Member\TestPublicationController@index',
        'as'=>'test.publications.index',
    ]);

    Route::post('/test/publications',[
        'uses'=>'Member\TestPublicationController@store',
        'as'=>'test.publications.store',
    ]);

    Route::delete('/test/publications/{id}',[
        'uses'=>'Member\TestPublicationController@destroy',
        'as'=>'test.publications.destroy',
    ]);

});


/******************************************************
 *     Admin Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['prefix' => 'admin','as' => 'admin.'],function () {

    Route::get('',[
        'uses'=>'Backend\DashboardController@index',
        'as'=>'show.index',
    ]);

    Route::get('login',[
        'uses'=>'Auth\Admin\LoginController@showLogin',
        'as'=>'show.login',
        //'middleware'=>'auth:admin',
    ]);

    Route::post('login',[
        'uses'=>'Auth\Admin\LoginController@login',
        'as'=>'login',
    ]);

    Route::get('logout',[
        'uses'=>'Auth\Admin\LoginController@logout',
        'as'=>'logout',
        //'middleware'=>'auth:admin',
    ]);

        /*
    | Web Routes Admin backend
    |--------------------------------------------------------------------------
    | CMS level routes
    */
    //
    Route::get('manage-cms',array(
        'uses'=>'Backend\CMSController@showManageCMS',
        'as'=>'show.manage-cms',
        'middleware' => 'auth:admin',
    ));

    //Page Preview
    Route::get('page-preview/{pageSlug}',[
        'uses' => 'Backend\CMSController@cms',
        'as'=>'show.page-preview',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/page-preview/',[
        'uses' => 'Backend\CMSController@index',
        'as'=>'show.page-preview-home',
        'middleware' => 'auth:admin',
    ]);


    //publishContent
    Route::post('publish_content/{id}',array(
        'uses'=>'Backend\CMSController@publishContent',
        'as'=>'publish_content',
        'middleware' => 'auth:admin',
    ));



    //nEW ROUTE FOR MENUS

    Route::prefix('ajax/page')->group(function () {
        Route::post('all',array(
            'uses'=>'Backend\CMSController@getMenus',
            'as'=>'ajax.get.pages',
            'middleware' => 'auth:admin',
        ));
        Route::post('create',array(
            'uses'=>'Backend\CMSController@createMenu',
            'as'=>'ajax.create.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('update',array(
            'uses'=>'Backend\CMSController@updateMenu',
            'as'=>'ajax.update.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('delete',array(
            'uses'=>'Backend\CMSController@deleteMenu',
            'as'=>'ajax.delete.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('dnd',array(
            'uses'=>'Backend\CMSController@dragAndDropMenu',
            'as'=>'ajax.dnd.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('detail',array(
            'uses'=>'Backend\CMSController@getPageDetail',
            'as'=>'ajax.get.page-detail',
            'middleware' => 'auth:admin',
        ));
        Route::post('update-page-detail',array(
            'uses'=>'Backend\CMSController@updatePage',
            'as'=>'ajax.update.page-detail',
            'middleware' => 'auth:admin',
        ));

        //footer menu
        Route::post('footer/all',array(
            'uses'=>'Backend\CMSController@getFooterMenus',
            'as'=>'ajax.get.footer-menus',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/create',array(
            'uses'=>'Backend\CMSController@createFooterMenu',
            'as'=>'ajax.create.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/update',array(
            'uses'=>'Backend\CMSController@updateFooterMenu',
            'as'=>'ajax.update.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/delete',array(
            'uses'=>'Backend\CMSController@deleteFooterMenu',
            'as'=>'ajax.delete.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/dnd',array(
            'uses'=>'Backend\CMSController@dragAndDropFooterMenu',
            'as'=>'ajax.dnd.footer-menu',
            'middleware' => 'auth:admin',
        ));
        //publishContent
        Route::post('publish',array(
            'uses'=>'Backend\CMSController@publishContent',
            'as'=>'ajax.publish.page',
            'middleware' => 'auth:admin',
        ));
    });


    //Manage Banner
    Route::get('/manage-banner/',[
        'uses' => 'Backend\CMSController@showManageBanner',
        'as'=>'show.manage-banner',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/create-banner/',[
        'uses' => 'Backend\CMSController@showCreateBanner',
        'as'=>'show.create-banner',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/edit-banner/{id}',[
        'uses' => 'Backend\CMSController@showEditBanner',
        'as'=>'show.edit-banner',
        'middleware' => 'auth:admin',
    ]);


    Route::post('/post-banner/',[
        'uses' => 'Backend\CMSController@postBanner',
        'as'=>'post.banner',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/update-banner/',[
        'uses' => 'Backend\CMSController@updateBanner',
        'as'=>'update.banner',
        'middleware' => 'auth:admin',

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Admin;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class AdminController extends Controller
{
    public function index()
    {
        $admins = Admin::all();
        return view('backend.admin.index',compact('admins'));
    }

    public function create()
    {
        $roles = Role::all();
        return view('backend.admin.create',compact('roles'));

    }

    public function edit($id)
    {
        //Edit Admin
        $admin =  Admin::findOrFail($id);
        $roles = Role::all();
        return view('backend.admin.edit',compact('admin','roles'));

    }

    public function store(Request $request)
    {


        $admin =  new Admin();
        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'email|max:255|unique:admins',

            'password' => 'required|string|min:6',

        ]);

        $admin->name =  $request->input('name');
        $admin->email = $request->input('email');
        $admin->role_id = $request->input('role_id');


        $admin->password = bcrypt($request->input('password'));

        $admin->save();


        $data = array('name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => $request->input('password')
        );

        Mail::send('emails.admin_details', $data, function ($message) {
            $message->to(Input::get('email'), 'HVSIA')
                ->subject('Administrator Details');
            $message->from(env('MAIL_FROM_ADDRESS', 'admin@hvsia.com'), 'HVSIA');
        });


        Session::flash('message', 'Administrator successfully Created!');
        return redirect()->route('admin.admins.index');

    }

    public function destroy(Request $request){
        $admin = Admin::findOrFail($request->id);
        if($admin->delete()){
            Session::flash('message','Admin Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        Admin::where('id',$id)->update($data);

        return redirect()->back()->with('message','Admin successfully Updated!');

    }
}

app/Http/Controllers/Backend/CompetencyAreaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\CompetencyArea;
use App\Role;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use App\FocusArea;

class CompetencyAreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $competency_areas = CompetencyArea::all();
        return view('backend.competency-area.index',compact('competency_areas'));
    }

    public function create()
    {
        return view('backend.competency-area.create');

    }

    public function edit($id)
    {
        //Edit CompetencyArea
        $competency_area =  CompetencyArea::findOrFail($id);
        return view('backend.competency-area.edit',compact('competency_area'));

    }

    public function store(Request $request)
    {

        $competency_area =  new CompetencyArea();
        $this->validate($request, [
            'name' => 'required|max:255',
        ]);

        $competency_area->name =  $request->input('name');

        $competency_area->save();


        return redirect()->route('admin.competency-areas.index');

    }

    public function show(Request $request,$id)
    {
        $competency_area = CompetencyArea::findOrFail($id);
        $focus_area = FocusArea::findOrFail($request->focus_area_id);
        return view('backend.competency-area.show',compact('competency_area','focus_area'));
    }

    public function destroy($id){
        $competency_area = CompetencyArea::findOrFail($id);
        if($competency_area->delete()){
            Session::flash('message','CompetencyArea Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        CompetencyArea::where('id',$id)->update($data);

        return redirect()->route('admin.competency-areas.index')->with('message','CompetencyArea successfully Updated!');

    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct() {
        $this->middleware('auth:admin');
    }

    public function  index(){
        
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/FocusAreaImageUploadController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FocusArea;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class FocusAreaImageUploadController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function update(Request $request,$id){

        $focus_area = FocusArea::findOrFail($id);
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileName = $focus_area->generateRandomName($focus_area->name, $file);
            Storage::disk('public')->put(config('filesystems.storage.focus_area_image_path') . $fileName, file_get_contents($file));

            $focus_area->image = $fileName;
            $focus_area->save();

        }

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/LocationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Location;
use App\Role;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class LocationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function index()
    {
        $locations = Location::all();
        return view('backend.location.index',compact('locations'));
    }

    public function create()
    {
        return view('backend.location.create');

    }

    public function edit($id)
    {
        //Edit Location
        $location =  Location::findOrFail($id);
        return view('backend.location.edit',compact('location'));

    }

    public function store(Request $request)
    {

        $location =  new Location();
        $this->validate($request, [
            'country' => 'required|max:255',
            'organization' => 'required|max:255',
        ]);

        $location->country =  $request->input('country');
        $location->organization =  $request->input('organization');


        $location->save();


        return redirect()->route('admin.locations.index');

    }

    public function destroy($id){
        $location = Location::findOrFail($id);
        if($location->delete()){
            Session::flash('message','Location Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        Location::where('id',$id)->update($data);

        return redirect()->route('admin.locations.index')->with('message','Location successfully Updated!');

    }
}

resources/views/backend/matrix-table/index.blade.php
@extends('layouts.backend.main')

@section('css')
    <!--
    PLEASE NOTE THAT THIS PAGE IS COMPLEX, LOTS OF NESTED ITERATIONS AND CONDITIONS
    BAD PRACTICE BUT GETS THE JOB DONE. CODE ON THIS PAGE CAN BE IMPROVED.

    I TRIED AS MUCH AS POSSIBLE TO COMMENT EVERY LOOP. ENJOYYYYY!!!!!

-->
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Matrix Table</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Matrix</a></li>
                <li class="breadcrumb-item active">Table</li>
            </ol>
        </div>

    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">

        <!-- begin row -->
        <div class="row">
            <!-- begin col-12 -->
            <div class="col-md-12">
                <!-- begin panel -->
                <div class="card" data-sortable-id="tree-view-4">
                    {{--<div class="card-body">
                        <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>

                                <th class="text-nowrap"></th>
                                <th class="text-nowrap">Structural Design</th>
                                <th class="text-nowrap">Materials</th>
                                <th class="text-nowrap">Functional Performance</th>
                                <th class="text-nowrap">Structural Performance</th>
                                <th class="text-nowrap">Rehabilitation Maintenance</th>
                                <th class="text-nowrap">Construction</th>
                                <th class="text-nowrap">Information Systems</th>
                                <th class="text-nowrap">Vehicle Pavement-Interaction</th>
                                <th class="text-nowrap">Instrumentation</th>
                                <th class="text-nowrap">Environ. Impact Assess</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="text-nowrap">Asphalt </td>
                                <td></td>
                                <td></td>
                                <td class="bg-success" align="center"> <i class="fa fa-check"></i> </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>

                            </tr>
                            <tr>
                                <td class="text-nowrap">Cemented layers</td>
                                <td></td>
                                <td></td>
                                <td class="bg-success" align="center"> <i class="fa fa-check"></i> </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>

                            </tr>
                            <tr>
                                <td class="text-nowrap">Concrete</td>
                                <td></td>
                                <td class="bg-success" align="center"> <i class="fa fa-check"></i> </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="bg-success" align="center"> <i class="fa fa-check"></i> </td>
                                <td></td>
                                <td></td>
                                <td></td>

                            </tr>
                            <tr>
                                <td  class="text-nowrap">Granular</td>
                                <td></td>
                                <td></td>
                                <td class="bg-success" align="center"> <i class="fa fa-check"></i> </td>
                                <td></td>
                                <td></td>
                                <td class="bg-success" align="center"> <i class="fa fa-check"></i> </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>

                            </tr>

                            </tbody>
                        </table>
                        </div>
                    </div>
--}}

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th class="text-nowrap"></th>
                                    <!--Loop through competency area and display-->
                                    @foreach($competency_areas as $row)
                                        <th class="text-nowrap">{{$row->name}}</th>
                                    @endforeach
                                </tr>
                                </thead>
                                <tbody>
                                <!--Loop through focus area and display-->
                                @foreach($focus_areas as $focus_area)
                                    <tr>
                                        <td class="text-nowrap">{{$focus_area->name}} </td><!--first loop must display focus area name-->
                                        <!--loop through competency area again to get each competency area-->
                                    @foreach($competency_areas as $competency_area)

                                        @if($focus_area->tests()->count() > 0)

                                            @php
                                                $test_array = [];
                                                $duplicate_array = [];
                                            @endphp

                                            <!-- loop tests under each focus area, one competency area can appear once in each test. I need to find a way to eliminate duplicate (Read on to see the logic used for elimination)-->
                                                @foreach($focus_area->tests as $test)
                                                    @php
                                                        //loop test competency areas,pluck only the name and append to test_array
                                                        foreach($test->competency_areas()->pluck('name')->toArray() as $n){
                                                            array_push($test_array,$n);
                                                        }

                                                    @endphp


                                                @endforeach

                                                <!--Now use array_count_values() to count existence of each name-->
                                                @php
                                                    $duplicate_array = array_count_values($test_array);
                                                @endphp


                                             <!--If competency area name exists as a key in duplicate_array AND exists 2 or more times in the duplicate_array,
                                             then check(meaning a test has been done or ongoing under the focus area and competency area)-->
                                                @if(array_key_exists($competency_area->name,$duplicate_array) && $duplicate_array[$competency_area->name] >= 2)
                                                    <td class="bg-success" align="center"> <a href="{{route('admin.competency-areas.show',['id' => $competency_area->id])}}?focus_area_id={{$focus_area->id}}"><i class="fa btn btn-block fa-check"></i></a></td>
                                                    <!--Else If competency area name exists as a key in duplicate_array AND exists once in the duplicate_array,
                                             then check(meaning a test has been done or ongoing under the focus area and competency area)-->
                                                @elseif(array_key_exists($competency_area->name,$duplicate_array) && $duplicate_array[$competency_area->name] == 1 )
                                                    <td class="bg-success" align="center"> <a href="{{route('admin.competency-areas.show',['id' => $competency_area->id])}}?focus_area_id={{$focus_area->id}}"><i class="fa btn btn-block fa-check"></i></a></td>
                                                    <!--Else competency area name  does not exist, therefore don't check -->
                                                @else
                                                    <td>  </td>
                                                @endif

                                            @else
                                                <td>  </td>
                                            @endif

                                    @endforeach

                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>



                </div>
                <!-- end panel -->
            </div>
            <!-- end col-6 -->
        </div>
        <!-- end row -->
    </div>

@endsection

@section('script')
    {{--@include('layouts.admin_script.faq_script')--}}

@endsection