routes/web.php
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

    //Email verification route
    $this->get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
    $this->get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
    $this->get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');


});


/******************************************************
 *     Member Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['prefix' => 'member','as' => 'member.'],function () {


    Route::get('',[
        'uses'=>'Member\DashboardController@index',
        'as'=>'show.index',
    ]);


    ////////// Manage Meetings //////////
    Route::get('/meetings',[
        'uses'=>'Member\MeetingController@index',
        'as'=>'meetings.index',
    ]);


    Route::get('/meetings/{id}',[
        'uses'=>'Member\MeetingController@show',
        'as'=>'meetings.show',
    ]);

    ////////// Manage Matrices //////////
    Route::get('/matrices',[
        'uses'=>'Member\MatrixController@index',
        'as'=>'matrices.index',
    ]);
    Route::get('/matrices/{id}',[
        'uses'=>'Member\MatrixController@show',
        'as'=>'matrices.show',
    ]);

    ////////// Manage Matrix tables //////////
    Route::get('/matrix/table',[
        'uses'=>'Member\MatrixTableController@index',
        'as'=>'matrix.tables.index',
    ]);



    ////////// Manage Competency Areas //////////
    Route::get('/competency-areas/{id}',[
        'uses'=>'Member\CompetencyAreaController@show',
        'as'=>'competency-areas.show',
    ]);

    ////////// Manage Test //////////
    /// Route::get('/matrices',[
    Route::get('/tests',[
        'uses'=>'Member\TestController@index',
        'as'=>'tests.index',
    ]);

    Route::get('/tests/{id}',[
        'uses'=>'Member\TestController@show',
        'as'=>'tests.show',
    ]);

    Route::post('/tests',[
        'uses'=>'Member\TestController@store',
        'as'=>'tests.store',
    ]);

    Route::put('/tests/{id}',[
        'uses'=>'Member\TestController@update',
        'as'=>'tests.update',
    ]);
    Route::delete('/tests/{id}',[
        'uses'=>'Member\TestController@destroy',
        'as'=>'tests.destroy',
    ]);


    ////////// Manage Meetings //////////

    Route::get('/test/publications',[
        'uses'=>'Member\TestPublicationController@index',
        'as'=>'test.publications.index',
    ]);

    Route::post('/test/publications',[
        'uses'=>'Member\TestPublicationController@store',
        'as'=>'test.publications.store',
    ]);

    Route::delete('/test/publications/{id}',[
        'uses'=>'Member\TestPublicationController@destroy',
        'as'=>'test.publications.destroy',
    ]);

});


/******************************************************
 *     Admin Routes                                   *
 *                                                    *
 ******************************************************/
Route::group(['prefix' => 'admin','as' => 'admin.'],function () {

    Route::get('',[
        'uses'=>'Backend\DashboardController@index',
        'as'=>'show.index',
    ]);

    Route::get('login',[
        'uses'=>'Auth\Admin\LoginController@showLogin',
        'as'=>'show.login',
        //'middleware'=>'auth:admin',
    ]);

    Route::post('login',[
        'uses'=>'Auth\Admin\LoginController@login',
        'as'=>'login',
    ]);

    Route::get('logout',[
        'uses'=>'Auth\Admin\LoginController@logout',
        'as'=>'logout',
        //'middleware'=>'auth:admin',
    ]);

        /*
    | Web Routes Admin backend
    |--------------------------------------------------------------------------
    | CMS level routes
    */
    //
    Route::get('manage-cms',array(
        'uses'=>'Backend\CMSController@showManageCMS',
        'as'=>'show.manage-cms',
        'middleware' => 'auth:admin',
    ));

    //Page Preview
    Route::get('page-preview/{pageSlug}',[
        'uses' => 'Backend\CMSController@cms',
        'as'=>'show.page-preview',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/page-preview/',[
        'uses' => 'Backend\CMSController@index',
        'as'=>'show.page-preview-home',
        'middleware' => 'auth:admin',
    ]);


    //publishContent
    Route::post('publish_content/{id}',array(
        'uses'=>'Backend\CMSController@publishContent',
        'as'=>'publish_content',
        'middleware' => 'auth:admin',
    ));



    //nEW ROUTE FOR MENUS

    Route::prefix('ajax/page')->group(function () {
        Route::post('all',array(
            'uses'=>'Backend\CMSController@getMenus',
            'as'=>'ajax.get.pages',
            'middleware' => 'auth:admin',
        ));
        Route::post('create',array(
            'uses'=>'Backend\CMSController@createMenu',
            'as'=>'ajax.create.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('update',array(
            'uses'=>'Backend\CMSController@updateMenu',
            'as'=>'ajax.update.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('delete',array(
            'uses'=>'Backend\CMSController@deleteMenu',
            'as'=>'ajax.delete.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('dnd',array(
            'uses'=>'Backend\CMSController@dragAndDropMenu',
            'as'=>'ajax.dnd.page',
            'middleware' => 'auth:admin',
        ));
        Route::post('detail',array(
            'uses'=>'Backend\CMSController@getPageDetail',
            'as'=>'ajax.get.page-detail',
            'middleware' => 'auth:admin',
        ));
        Route::post('update-page-detail',array(
            'uses'=>'Backend\CMSController@updatePage',
            'as'=>'ajax.update.page-detail',
            'middleware' => 'auth:admin',
        ));

        //footer menu
        Route::post('footer/all',array(
            'uses'=>'Backend\CMSController@getFooterMenus',
            'as'=>'ajax.get.footer-menus',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/create',array(
            'uses'=>'Backend\CMSController@createFooterMenu',
            'as'=>'ajax.create.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/update',array(
            'uses'=>'Backend\CMSController@updateFooterMenu',
            'as'=>'ajax.update.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/delete',array(
            'uses'=>'Backend\CMSController@deleteFooterMenu',
            'as'=>'ajax.delete.footer-menu',
            'middleware' => 'auth:admin',
        ));
        Route::post('footer/dnd',array(
            'uses'=>'Backend\CMSController@dragAndDropFooterMenu',
            'as'=>'ajax.dnd.footer-menu',
            'middleware' => 'auth:admin',
        ));
        //publishContent
        Route::post('publish',array(
            'uses'=>'Backend\CMSController@publishContent',
            'as'=>'ajax.publish.page',
            'middleware' => 'auth:admin',
        ));
    });


    //Manage Banner
    Route::get('/manage-banner/',[
        'uses' => 'Backend\CMSController@showManageBanner',
        'as'=>'show.manage-banner',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/create-banner/',[
        'uses' => 'Backend\CMSController@showCreateBanner',
        'as'=>'show.create-banner',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/edit-banner/{id}',[
        'uses' => 'Backend\CMSController@showEditBanner',
        'as'=>'show.edit-banner',
        'middleware' => 'auth:admin',
    ]);


    Route::post('/post-banner/',[
        'uses' => 'Backend\CMSController@postBanner',
        'as'=>'post.banner',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/update-banner/',[
        'uses' => 'Backend\CMSController@updateBanner',
        'as'=>'update.banner',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/update-banner-image/',[
        'uses' => 'Backend\CMSController@updateBannerImage',
        'as'=>'update.banner-image',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/update-banner-icon/',[
        'uses' => 'Backend\CMSController@updateBannerIcon',
        'as'=>'update.banner-icon',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/delete-banner',[
        'uses' => 'Backend\CMSController@deleteBanner',
        'as'=>'delete.banner',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/publish-banner/{id}',[
        'uses' => 'Backend\CMSController@updateStatus',
        'as'=>'post.publish-banner',
        'middleware' => 'auth:admin',
    ]);

    //Manage Gallery
    Route::get('/manage-gallery/',[
        'uses' => 'Backend\CMSController@showManageGallery',
        'as'=>'show.manage-gallery',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/create-gallery/',[
        'uses' => 'Backend\CMSController@showCreateGallery',
        'as'=>'show.create-gallery',
        'middleware' => 'auth:admin',
    ]);

    Route::get('/edit-gallery/{id}',[
        'uses' => 'Backend\CMSController@showEditGallery',
        'as'=>'show.edit-gallery',
        'middleware' => 'auth:admin',
    ]);


    Route::post('/post-gallery/',[
        'uses' => 'Backend\CMSController@postGallery',
        'as'=>'post.gallery',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/update-gallery/',[
        'uses' => 'Backend\CMSController@updateGallery',
        'as'=>'update.gallery',
        'middleware' => 'auth:admin',
    ]);

    Route::post('/delete-gallery',[

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $fillable = [
        'country','organization',
    ];

    public function users(){
        return $this->hasMany('App\Location','location_id');
    }

    public function tests(){
        return $this->hasMany('App\Test','location_id');
    }

    public function getLocationAttribute(){
        return $this->country . ':' . $this->organization;
    }

    public function completedTests(){
        return $this->tests()->where('completed',true)->get();
    }

    public function inProgressTests(){
        return $this->tests()->where('completed',false)->get();
    }
}

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Admin;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class AdminController extends Controller
{
    public function index()
    {
        $admins = Admin::all();
        return view('backend.admin.index',compact('admins'));
    }

    public function create()
    {
        $roles = Role::all();
        return view('backend.admin.create',compact('roles'));

    }

    public function edit($id)
    {
        //Edit Admin
        $admin =  Admin::findOrFail($id);
        $roles = Role::all();
        return view('backend.admin.edit',compact('admin','roles'));

    }

    public function store(Request $request)
    {


        $admin =  new Admin();
        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'email|max:255|unique:admins',

            'password' => 'required|string|min:6',

        ]);

        $admin->name =  $request->input('name');
        $admin->email = $request->input('email');
        $admin->role_id = $request->input('role_id');


        $admin->password = bcrypt($request->input('password'));

        $admin->save();


        $data = array('name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => $request->input('password')
        );

        Mail::send('emails.admin_details', $data, function ($message) {
            $message->to(Input::get('email'), 'HVSIA')
                ->subject('Administrator Details');
            $message->from(env('MAIL_FROM_ADDRESS', 'admin@hvsia.com'), 'HVSIA');
        });


        Session::flash('message', 'Administrator successfully Created!');
        return redirect()->route('admin.admins.index');

    }

    public function destroy(Request $request){
        $admin = Admin::findOrFail($request->id);
        if($admin->delete()){
            Session::flash('message','Admin Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        Admin::where('id',$id)->update($data);

        return redirect()->back()->with('message','Admin successfully Updated!');

    }
}

app/Http/Controllers/Backend/CompetencyAreaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\CompetencyArea;
use App\Role;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use App\FocusArea;

class CompetencyAreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $competency_areas = CompetencyArea::all();
        return view('backend.competency-area.index',compact('competency_areas'));
    }

    public function create()
    {
        return view('backend.competency-area.create');

    }

    public function edit($id)
    {
        //Edit CompetencyArea
        $competency_area =  CompetencyArea::findOrFail($id);
        return view('backend.competency-area.edit',compact('competency_area'));

    }

    public function store(Request $request)
    {

        $competency_area =  new CompetencyArea();
        $this->validate($request, [
            'name' => 'required|max:255',
        ]);

        $competency_area->name =  $request->input('name');

        $competency_area->save();


        return redirect()->route('admin.competency-areas.index');

    }

    public function show(Request $request,$id)
    {
        $competency_area = CompetencyArea::findOrFail($id);
        $focus_area = FocusArea::findOrFail($request->focus_area_id);
        return view('backend.competency-area.show',compact('competency_area','focus_area'));
    }

    public function destroy($id){
        $competency_area = CompetencyArea::findOrFail($id);
        if($competency_area->delete()){
            Session::flash('message','CompetencyArea Successfully Deleted');
            return redirect()->back();
        }
    }


    public function update(Request $request,$id)
    {

        $data = $request->except(['_token','_method']);


        //Update Page
        CompetencyArea::where('id',$id)->update($data);

        return redirect()->route('admin.competency-areas.index')->with('message','CompetencyArea successfully Updated!');

    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct() {
        $this->middleware('auth:admin');
    }

    public function  index(){
        
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/FocusAreaImageUploadController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FocusArea;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class FocusAreaImageUploadController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function update(Request $request,$id){

        $focus_area = FocusArea::findOrFail($id);
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileName = $focus_area->generateRandomName($focus_area->name, $file);
            Storage::disk('public')->put(config('filesystems.storage.focus_area_image_path') . $fileName, file_get_contents($file));

            $focus_area->image = $fileName;
            $focus_area->save();

        }

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/MarkTestCompletedController.php
<?php

namespace App\Http\Controllers\Backend;

use App\CompetencyArea;
use App\FocusArea;
use App\Location;
use App\Meeting;
use App\Test;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class MarkTestCompletedController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function update(Request $request,$id){
        //dd($id);
        $test = Test::findOrFail($id);
        $test->completed = true;
        $test->completed_date = Carbon::now();
        $test->save();

        return response()->json(['url' => route('admin.tests.index')]);
    }


}

app/Http/Controllers/Backend/MatrixController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MatrixController extends Controller
{
    public function  ShowManageMatrix(){
        return view('backend.matrix.ManageMatrix');
    }
    public function  ShowCreateTest(){
        return view('backend.matrix.CreateTest');
    }
    public function  ShowFocusArea(){
        return view('backend.matrix.FocusArea');
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.backend.main')

@section('css')
    {{-- @include('layouts.admin_css.faq_css')--}}

    <link href="{{asset('Back-Assets/assets/plugins/gritter/css/jquery.gritter.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="{{asset('Back-Assets/css/custom.css')}}" type="text/css" media="screen">

@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Manage User</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Content</a></li>
                <li class="breadcrumb-item active">Manage User</li>
            </ol>
        </div>

    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">

        <!-- begin row -->
        <div class="row">
            <!-- begin col-12 -->
            <div class="col-md-12">
                <!-- begin panel -->
                <div class="card" data-sortable-id="tree-view-4">
                    <div class="card-body">

                        <h4> Fill in the form </h4>
                        {{--@if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif--}}
                    </div>
                    <div class="card-body">
                        <form action="{{route('admin.users.store')}}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label class="control-label">First Name <span class="text-danger">*</span></label>
                                <input type="text" id="first-name" name="first_name" class="form-control {{ $errors->has('first_name') ? ' is-invalid' : '' }}" required value="{{old('first_name')}}">
                                @if ($errors->has('first_name'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('first_name') }} </strong>
                                            </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="control-label">Last Name <span class="text-danger">*</span></label>
                                <input type="text" id="last-name" name="last_name" class="form-control {{ $errors->has('last_name') ? ' is-invalid' : '' }}" required value="{{old('last_name')}}">
                                @if ($errors->has('last_name'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('last_name') }} </strong>
                                            </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="control-label">User Email <span class="text-danger">*</span></label>
                                <input type="text" id="email" name="email" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" required value="{{old('email')}}">
                                @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('email') }} </strong>
                                            </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="control-label">Phone Number </label>
                                <input type="text" id="phone-number" name="phone_number" class="form-control {{ $errors->has('phone_number') ? ' is-invalid' : '' }}" required value="{{old('phone_number')}}">
                                @if ($errors->has('phone_number'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('phone_number') }} </strong>
                                            </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="control-label">Location <span class="text-danger">*</span></label>
                                <select name="location_id" class="form-control {{ $errors->has('location_id') ? ' is-invalid' : '' }}">
                                    @foreach($locations as $row)
                                        <option value="{{$row->id}}" {{$row->id==old('location_id')?'selected' : ''}}>{{$row->location}}</option>
                                    @endforeach

                                </select>
                                @if ($errors->has('location_id'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('location_id') }} </strong>
                                            </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="control-label">Password <span class="text-danger">*</span></label></label>
                                <input type="text" id="password" name="password" class="form-control" >
                            </div>
                            <button type="submit" class="btn waves-effect btn-block waves-light btn-rounded btn-info pull-right"><i class="fa fa-plus"></i> Create New User</button>
                            <br/>
                        </form>

                    </div>



                </div>
                <!-- end panel -->
            </div>
            <!-- end col-6 -->
        </div>
        <!-- end row -->


        @endsection

        @section('script')
            {{--@include('layouts.admin_script.faq_script')--}}

            <script src="{{asset('Back-Assets/assets/plugins/jquerytree/jquery.tree.min.js')}}"></script>
            <script src="{{asset('Back-Assets/js/custom.min.js')}}"></script>
            <script src="{{asset('Back-Assets/js/jasny-bootstrap.js')}}"></script>

@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.backend.main')

@section('css')
    {{-- @include('layouts.admin_css.faq_css')--}}

    <link href="{{asset('Back-Assets/assets/plugins/gritter/css/jquery.gritter.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="{{asset('Back-Assets/css/custom.css')}}" type="text/css" media="screen">

@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Manage User</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Content</a></li>
                <li class="breadcrumb-item active">Manage User</li>
            </ol>
        </div>

    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">

        <!-- begin row -->
        <div class="row">
            <!-- begin col-12 -->
            <div class="col-md-12">
                <!-- begin panel -->
                <div class="card" data-sortable-id="tree-view-4">
                    <div class="card-body">

                        <h4> Fill in the form </h4>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
                    <div class="card-body">
                        <form action="{{route('admin.users.update',['id' => $user->id])}}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="control-label">First Name <span class="text-danger">*</span></label>
                                <input type="text" id="first-name" name="first_name" class="form-control" value="{{$user->first_name}}" required >
                            </div>
                            <div class="form-group">
                                <label class="control-label">Last Name <span class="text-danger">*</span></label>
                                <input type="text" id="last-name" name="last_name" class="form-control" value="{{$user->last_name}}" required >
                            </div>
                            <div class="form-group">
                                <label class="control-label">User Email <span class="text-danger">*</span></label>
                                <input type="text" id="email" name="email" class="form-control" value="{{$user->email}}" required >
                            </div>
                            <div class="form-group">
                                <label class="control-label">Phone Number </label>
                                <input type="text" id="phone-number" name="phone_number" class="form-control {{ $errors->has('phone_number') ? ' is-invalid' : '' }}" required value="{{$user->phone_number}}">
                                @if ($errors->has('phone_number'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('phone_number') }} </strong>
                                            </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="control-label">Location <span class="text-danger">*</span></label>
                                <select name="location_id" class="form-control">
                                    @foreach($locations as $row)
                                        <option value="{{$row->id}}" {{$row->id==$user->location_id?'selected' : ''}}>{{$row->location}}</option>
                                    @endforeach

                                </select>
                                @if ($errors->has('location_id'))
                                    <span class="invalid-feedback">
                                              <strong>{{ $errors->first('location_id') }} </strong>
                                            </span>
                                @endif
                            </div>

                            <button type="submit" class="btn waves-effect btn-block waves-light btn-rounded btn-info pull-right"> Update</button>
                            <br/>
                        </form>

                    </div>

                </div>
                <!-- end panel -->
            </div>
            <!-- end col-6 -->
        </div>
        <!-- end row -->


        @endsection

        @section('script')
            {{--@include('layouts.admin_script.faq_script')--}}

            <script src="{{asset('Back-Assets/assets/plugins/jquerytree/jquery.tree.min.js')}}"></script>
            <script src="{{asset('Back-Assets/js/custom.min.js')}}"></script>
            <script src="{{asset('Back-Assets/js/jasny-bootstrap.js')}}"></script>

@endsection